sudo: false
bundler_args: --retry 3
language: node_js
node_js:
  - 0.12
cache:
  directories:
    - node_modules/
addons:
  firefox: '43.0'
install:
  - npm set progress=false
  - travis_retry npm install
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script:
  - npm run example
